apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-number-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: random-number-api
  template:
    metadata:
      labels:
        app: random-number-api
    spec:
      containers:
      - name: random-number-api
        image: aaghamohammadi/random-number-api:1.0.0
        ports:
        - containerPort: 5000  
